### PR TITLE
Update Mavrrick.Goveev2KettleDriver.groovy with user defined polling schedule.

### PR DESCRIPTION
**Pull request by KurtSanders**
I made a few updates to your excellent driver for the Govee Kettle appliance.  I added new user defined polling on/off time periods to reduce the frequency of polling when it is not needed, added a field for modeDescription, activePollingPeriod, lastPollActivity, stopAllPolling command.  Also added one bug fix for missing gear value with a defauft value of 0 if null is sent.  If this works for you, you can merge otherwise just look over and decide.

### CODE REVIEW

**Comment by Mavrrick** [comment]
I really like most of what was done here. But i have a few questions/statements.

1. What happens if a user doesn't set the Start and End polling time. It doesn't appear to have defaults and I wouldn't want to break users that haven't set it if this rolls out and they don't add those values.
2. I see you created a Attribute value with modeDescription as values. That isn't a bad idea, but will likely trigger more updates Govee has a few kettles and so i have avoided things that may be specific to a model. I don't see a problem with it, but could easily trigger more updates. 
3. I will need to review the other drivers for modeDescription as well. Most of the drivers i have avoided being specific like this for the Working mode command because it is used and the value and such change between humidifiers, dehumidifiers, fans, icemakers, kettles, ect. It is a heavily used command overall in the cloud for non light devices. So if this got implemented it would trigger updates across allot of other devices. 
4. What did you use to determine that polling every 15 seconds would break Hubitat. I agree that is to quick, but just curious how you derived that as a value. 

What is the perceived value of setting polling time vs just setting a polling and running it 24/7. I would expect some users will want to be able to use the device at any time. I also get that it may be nice to poll at short intervals over specific time if you know you will only use it like between 8am and noon local time. 

Lastly i would assume you have tested all of this stuff as well in your own environment. I don't have a Kettle to test with so i would be completely dependent on users to validate these changes.

**Comment by Mavrrick** [comment]
I need to do a little bit better at reading. It looks like you did answer my question about value. So really all I need to know is about question comment #1 What happens if a user already has a kettle and installs this driver and doesn't set the start and end time. I don't see anything that shows that it accommodate that condition and just blow up the pooling. That said I literally picked up programing just for Smartthings and Hubitat so this isn't something I learned in a structured environment. I could certainly be missing something that explains it.

**Comment by KurtSanders** [comment]
The two time fields are required and will not let the user proceed unless they input times.  It checks to make sure the begin time is before the end time.  These same two fields are also initially defaulted to 8-5 (I think) so that polling will happen even if they forget to set it when they setup their kettle for the first time.  Since Govee restricts the polling to 10,000 polls per day, one can use quite a few of these when they do not need to, especially if they have other Govee products, so this attempts to only poll when one is going to need water.  I have mine setup to be 3am to 4pm and it has been working for a month.  

If you want to chat via phone, PM me on Hubitat and I will send you my phone number.  I am kurtsanders on Hubitat.

Your code is very good!

**Comment by Mavrrick** [comment]
OK so this is a breaking change for users that already have a Kettle device installed if they just update and don't go in and intentionally set those values.

Would it be possible to set something up so that if those values are blank to simply go from midnight to midnight. instead of just breaking. That would prevent existing users from breaking when they upgrade.

If you do that I will merge it immediately. 

I am also wondering about merging this method into other devices to give uesrs more control of the API Rate Limit usage.

**Comment by KurtSanders** [comment]
The default polling time values (if null) are set below when the kettle driver is first installed and so it does not break when first installed:
    device.updateSetting('pollStartDateTime', [type: "time", value: timeToday("06:00")])
    device.updateSetting('pollEndDateTime',   [type: "time", value: timeToday("18:00")])
    device.updateSetting('pollRate', [type: "number", value: 300])
 
We can agree to set them to whatever start & end default you feel needed.  It's just if the default is 24 hours, then do we really accomplishment anything from polling  7x24 everyday.  As I stated before, Govee has a limitation on polling for ALL Govee devices per API string and one will hit that limit if unlimited rapid polling is used and they have other Govee devices that require polling.  Some Govee device users will hit that max limit and then they will have to reduce polling frequency rather than keep the frequency and only poll when it is needed.  Just my two cents and if you prefer not to merge, that's OK.  I was just trying to share a smarter means of polling when the service provider has maximums.  Otherwise, I would poll ever second for the best response.  Maybe someday, Govee will include the Kettle in a websocket response, so blind polling (which is archaic) will be eliminated.

**Comment by Mavrrick** [comment]
I agree with everything you are saying about the rate limits that are in place. That is partially why I have them default to 5 min because that should give users by default a decent amount of devices before it becomes to much of a issue,

My only concern is around users that have already installed the Kettle and won't have those values when the update is released. I could publish a update note saying to go in and populate that value, but everyone may not read that.

**Comment by KurtSanders** [comment]
That would be good when you update your repository.json, since it is prudent that they set the polling times, if anything to also avoid a high Hub CPU rate on their overburdened hub for needless Govee server polling when they don't boil water.  If we can get a previously installed user to test the Kettle driver, that would be great..  New users will not have to worry as the polling will occur from 6am - 6pm.  If they don't get hubitat kettle notifications outside this default polling, we can inform them to increase the polling start/end time to meet their needs.

If this change causes havoc on your installed kettle users, I will be happy to work with them, as I do with my installed apps, via a DM, and updates so we all can get the best results.

Again, GREAT work on the the GOVEE integration, quite a feather in your cap!

**Pull request merged**
